timezone: Europe/Oslo
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
title: H책vard Pedersen
description: Hjemmeside og blogg for H책vard Pedersen
url: https://fuzzy76.net
author: H책vard Pedersen
logo: /apple-touch-icon.png
twitter:
  username: fuzzy76
social:
  name: H책vard Pedersen
  links:
    - https://twitter.com/fuzzy76
    - https://www.facebook.com/fuzzy76
    - https://www.linkedin.com/in/haavardp/
    - https://www.strava.com/athletes/6902791
    - https://github.com/fuzzy76
    - https://www.goodreads.com/user/show/70089200-h-vard-pedersen
google_site_verification: 1234
lang: nb_NO
feed:
  path: feed/index.xml
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:slug/
  -
    scope:
      path: ""
    values:
      image: /apple-touch-icon.png